esphome:
  name: schneider-pm2230
  friendly_name: PM2230

esp32:
  board: esp32dev
  framework:
    type: arduino

globals:
  # Enable variable restore from RTC memory (ESP8266 only)
  # Daily export base variable will not survive a power cycle, only reboots.
  - id: daily_export_base
    type: float
    restore_value: yes
    initial_value: '-1'

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "cqv0WUXhhp2eEJc9ERLBRjh8mM+m6HdeVZTHkYUDbKY="

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-67Ea04"
    password: "wYH893Mzb9CV"

captive_portal:

web_server:



time:
  - platform: homeassistant
    id: esptime
  - platform: sntp
    on_time:
      # Reset all four daily import counters at midnight
      # This will also force the command_result id to be updated
      # Validation check could be performed on command_result sensor
      # 0 = valid operation (reset all partial registers - ok)
      # 3000 = invalid operation (reset all partial registers - nok) )
      - seconds: 59
        minutes: 59
        hours: 23
        days_of_week: MON-SUN
        then:
          - component.update: PM2230_daily

binary_sensor:
  - platform: status
    name: "Energy Meter Status"
    id: system_status

uart:
  id: mod_bus
  rx_pin: 17
  tx_pin: 16
  baud_rate: 19200
  parity: EVEN
  stop_bits: 1
  # Optional debug parameter if rx/tx uart hex data is needed for debugging  
  #debug:

modbus:
  id: modbus1

modbus_controller:
  - id: PM2230
    address: 0x1
    modbus_id: modbus1
    # Update all, but Total Active, energy sensors every minute
    update_interval: 60s
    
  - id: PM2230_freq
    address: 0x1
    modbus_id: modbus1
    # Update Total Active Energy sensor frequently (10 seconds interval)
    update_interval: 10s  
  
  - id: PM2230_daily
    address: 0x1
    modbus_id: modbus1
    # No interval sensor update !
    # Only custom_command sensor is using this id (once daily at midnight)
    update_interval: never  
    
sensor:
  - platform: modbus_controller
    modbus_controller_id: PM2230
    name: "L1 Active Power"
    id: power_l1
    register_type: holding
    address: 3053
    unit_of_measurement: "Wh"
    device_class: energy
    value_type: FP32
    filters:
      - multiply: 1000
    accuracy_decimals: 0
    
  - platform: modbus_controller
    modbus_controller_id: PM2230
    name: "L2 Active Power"
    id: power_l2
    register_type: holding
    address: 3055
    unit_of_measurement: "Wh"
    device_class: energy
    value_type: FP32
    filters:
      - multiply: 1000
    accuracy_decimals: 0
    
  - platform: modbus_controller
    modbus_controller_id: PM2230
    name: "L3 Active Power"
    id: power_l3
    register_type: holding
    address: 3057
    unit_of_measurement: "Wh"
    device_class: energy
    value_type: FP32
    filters:
      - multiply: 1000
    accuracy_decimals: 0
    
  - platform: modbus_controller
    modbus_controller_id: PM2230
    name: "Total Active Power"
    id: power_total
    register_type: holding
    address: 3059
    unit_of_measurement: "Wh"
    device_class: energy
    value_type: FP32
    filters:
      - multiply: 1000
    accuracy_decimals: 0
   
  - platform: modbus_controller
    modbus_controller_id: PM2230
    name: "Power Factor"
    id: power_factor
    register_type: holding
    address: 3083
    value_type: FP32
    accuracy_decimals: 2
    ## Possible float values from: -2 to +1
  
  - platform: modbus_controller
    modbus_controller_id: PM2230
    name: "Voltage avg. All Phases"
    id: voltage_avg
    register_type: holding
    address: 3035
    icon: mdi:sine-wave
    unit_of_measurement: "V"
    value_type: FP32
    accuracy_decimals: 0
    
  - platform: modbus_controller
    modbus_controller_id: PM2230
    name: "Frequency"
    id: frequency
    register_type: holding
    address: 3109
    icon: mdi:sine-wave
    unit_of_measurement: "Hz"
    value_type: FP32
    accuracy_decimals: 0

  - platform: total_daily_energy
    name: "PM2230 Daily Consumption"
    power_id: power_total
    filters:
        # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
    unit_of_measurement: kWh
    device_class: energy

  - platform: modbus_controller
    modbus_controller_id: PM2230
    name: "Number of Power Failures"
    id: "NoPowerFailures"
    register_type: read
    address: 1829
    icon: mdi:sail-boat-sink
    value_type: U_WORD
    accuracy_decimals: 0

  - platform: modbus_controller
    modbus_controller_id: PM2230
    name: "Duration of last Power Failure"
    id: "DurationofLastPowerFailure"
    register_type: holding
    address: 1834
    icon: mdi:sail-boat-sink
    value_type: U_DWORD
    accuracy_decimals: 0





text_sensor:
  - platform: modbus_controller
    modbus_controller_id: PM2230
    name: "Date/Time of Last Power Failure"
    id: "DateTimeLastPowerFailure"
    register_type: holding
    address: 1830
    icon: mdi:sail-boat-sink

  - platform: modbus_controller
    modbus_controller_id: PM2230
    name: "Firmware Version"
    id: "FirmwareVersion"
    register_type: holding
    address: 1637
    icon: mdi:calendar-range
